package com.an.biometric;

public enum BiometricError{
    BIOMETRIC_SDK_NOT_SUPPORTED,
    BIOMETRIC_NOT_SUPPORTED,
    BIOMETRIC_NOT_AVAILABLE,
    BIOMETRIC_NOT_PERMISSION_NOT_GRANTED,
    BIOMETRIC_INTERNAl_ERROR,
    AUTHENTICATION_FAILED,
    AUTHENTICATION_CANCELLED,
    AUTHENTICATION_HELP,
    AUTHENTICATION_ERROR


}